spring: 

  datasource: 

    username: book_store
    password: bookstore 

    url: jdbc:mysql://localhost:3306/book_store 



  jpa:  

    hibernate: 

     ddl-auto: update 

    show-sql: true
    